services:
  backend:
    build: ./backend
    container_name: easyabroad-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailhog
    volumes:
      - ./backend:/app            # ← mount your local code into the container
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - ./.env                    # ← load your host .env into the container

  frontend:
    build: ./frontend
    container_name: easyabroad-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  db:
    image: mysql:8.0
    container_name: easyabroad-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: armani
      MYSQL_DATABASE: easyabroad
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d:ro

  mailhog:
    image: mailhog/mailhog
    container_name: easyabroad-mailhog
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP

volumes:
  db-data: