version: "3.8"

services:
  backend:
    build: ./backend
    container_name: easyabroad-backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    volumes:
      - ./backend:/app
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    working_dir: /app
    environment:
      # Must match what 02_native_plugin.sql expects below:
      DB_HOST:        easyabroad-db
      DB_USER:        user
      DB_PASSWORD:    userpassword
      DB_NAME:        easyabroad

      JWT_SECRET:     armani
      JWT_ALGORITHM:  HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS:   7

      EMAIL_HOST:     mailhog
      EMAIL_PORT:     "1025"
      EMAIL_FROM:     no-reply@easyabroad.com

      FRONTEND_BASE_URL: http://localhost:8080

  frontend:
    build:
      context: .  #root of the project
      dockerfile: frontend/Dockerfile
    container_name: easyabroad-frontend
    ports:
      - "8080:80"


  db:
    image: mysql:8.0
    container_name: easyabroad-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: armani
      MYSQL_DATABASE:      easyabroad
      MYSQL_USER:          user
      MYSQL_PASSWORD:      userpassword
      MYSQL_ROOT_HOST:     "%"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro

  mailhog:
    image: mailhog/mailhog
    container_name: easyabroad-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db-data:
