
services:
  backend:
    build: ./backend
    container_name: easyabroad-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailhog
    volumes:
      - ./backend:/app            # mount your local code into the container
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      # Database settings
      DB_HOST:        easyabroad-db
      DB_USER:        user
      DB_PASSWORD:    userpassword
      DB_NAME:        easyabroad

      # JWT settings
      JWT_SECRET:     armani
      JWT_ALGORITHM:  HS256

      # Email settings
      EMAIL_HOST:     mailhog
      EMAIL_PORT:     "1025"
      EMAIL_FROM:     no-reply@easyabroad.com

      # Frontend URL
      FRONTEND_BASE_URL: http://localhost:8080

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: easyabroad-frontend
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: easyabroad-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: armani
      MYSQL_DATABASE:      easyabroad
      MYSQL_USER:          user
      MYSQL_PASSWORD:      userpassword
      MYSQL_ROOT_HOST:     "%"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d:ro

  mailhog:
    image: mailhog/mailhog
    container_name: easyabroad-mailhog
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP

volumes:
  db-data:
