CREATE TABLE IF NOT EXISTS Internship (
  user_id INT PRIMARY KEY,
  city_of_internship VARCHAR(255),
  country_of_internship VARCHAR(255),
  company_name VARCHAR(255),
  department_name VARCHAR(255),
  internship_start DATETIME,
  internship_finish DATETIME,
  proof_of_internship VARCHAR(255),
  accommodation BOOLEAN,
  social_life BOOLEAN,
  company_info BOOLEAN,
  travel_info BOOLEAN,
  zoom BOOLEAN,
  microsoft_teams BOOLEAN,
  google_meet BOOLEAN,
  apple_facetime BOOLEAN,
  is_verified BOOLEAN,
  verified_by INT,
  verified_at DATETIME,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (verified_by) REFERENCES users(id),
  FOREIGN KEY (country_of_internship) REFERENCES countries(country_name)
);
